# Generated by Django 6.1.1 on 2026-09-25 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название автомобиля')),
                ('price_per_day', models.IntegerField(verbose_name='Стоимость суток (₽)')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='Фото автомобиля')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='Марка')),
                ('body_type', models.CharField(blank=True, max_length=50, verbose_name='Кузов')),
                ('transmission', models.CharField(blank=True, max_length=50, verbose_name='Коробка')),
                ('drive', models.CharField(blank=True, max_length=50, verbose_name='Привод')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('engine_volume', models.CharField(blank=True, max_length=50, verbose_name='Объём двигателя')),
                ('power', models.CharField(blank=True, max_length=50, verbose_name='Мощность двигателя')),
                ('seats', models.IntegerField(blank=True, null=True, verbose_name='Пассажирских мест')),
                ('consumption', models.CharField(blank=True, max_length=50, verbose_name='Расход топлива')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'permissions': [('can_view_price', '💰 Бааны көрүү (баа жашырылбайт)'), ('can_publish_car', '🚗 Унааны жарыялоо (сайтка чыгаруу)'), ('can_hide_car', '🙈 Унааны жашыруу (is_available=False)')],
            },
        ),
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название услуги')),
                ('price', models.IntegerField(default=0, verbose_name='Цена (₽). 0 = бесплатно')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатно')),
            ],
            options={
                'verbose_name': 'Дополнительная услуга',
                'verbose_name_plural': 'Дополнительные услуги',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='promotions/', verbose_name='Фото')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'permissions': [('can_activate_promotion', '🎯 Акцияны иштетүү (is_active=True)'), ('can_feature_promotion', '⭐ Акцияны башкы бетке чыгаруу')],
            },
        ),
        migrations.CreateModel(
            name='RentalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(verbose_name='Номер шага')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Шаг аренды',
                'verbose_name_plural': 'Шаги аренды',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('rating', models.IntegerField(default=5, verbose_name='Рейтинг (1-5)')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('platform', models.CharField(choices=[('yandex', 'Яндекс Карты'), ('2gis', '2ГИС'), ('google', 'Google Maps')], default='yandex', max_length=20, verbose_name='Платформа')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-date'],
                'permissions': [('can_publish_review', '⭐ Отзывду жарыялоо (is_published=True)'), ('can_hide_review', '🙈 Отзывду жашыруу'), ('can_reply_review', '💬 Отзывга жооп жазуу')],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/', verbose_name='Фото')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rentcar.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Фото автомобиля',
                'verbose_name_plural': 'Фото автомобилей',
            },
        ),
        migrations.CreateModel(
            name='CarPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_from', models.IntegerField(verbose_name='От (дней)')),
                ('days_to', models.IntegerField(blank=True, null=True, verbose_name='До (дней)')),
                ('price_per_day', models.IntegerField(verbose_name='Цена за сутки (₽)')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='rentcar.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Цена автомобиля',
                'verbose_name_plural': 'Цены автомобилей',
                'ordering': ['days_from'],
                'permissions': [('can_change_price', '💵 Бааны өзгөртүү (таблицадагы баалар)')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name='ФИО клиента')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон клиента')),
                ('start_date', models.DateField(verbose_name='Дата начала аренды')),
                ('end_date', models.DateField(verbose_name='Дата окончания аренды')),
                ('delivery_time', models.TimeField(blank=True, null=True, verbose_name='Время подачи')),
                ('delivery_place', models.CharField(choices=[('city', 'город'), ('airport', 'аэропорт')], default='city', max_length=20, verbose_name='Место подачи')),
                ('total_price', models.IntegerField(default=0, verbose_name='Итого (₽)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar.car', verbose_name='Выберите автомобиль')),
                ('extra_services', models.ManyToManyField(blank=True, to='rentcar.extraservice', verbose_name='Дополнительные услуги')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
                'permissions': [('can_view_all_bookings', '📋 Баардык брондорду көрүү'), ('can_confirm_booking', '✅ Броньду ырастоо'), ('can_cancel_booking', '❌ Броньду жокко чыгаруу'), ('can_export_bookings', "📤 Брондорду Excel'ге экспорттоо")],
            },
        ),
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название места')),
                ('image', models.ImageField(upload_to='places/', verbose_name='Главное фото')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Краткое описание')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Продолжительность маршрута')),
                ('distance', models.CharField(blank=True, max_length=100, verbose_name='Расстояние от Горно-Алтайска')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('recommended_cars', models.ManyToManyField(blank=True, related_name='places', to='rentcar.car', verbose_name='Подходящие автомобили')),
            ],
            options={
                'verbose_name': 'Достопримечательность',
                'verbose_name_plural': 'Достопримечательности',
                'permissions': [('can_publish_place', '🏔️ Жерди жарыялоо (сайтка чыгаруу)'), ('can_feature_place', '⭐ Жерди башкы бетке чыгаруу')],
            },
        ),
        migrations.CreateModel(
            name='TouristPlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/gallery/', verbose_name='Фото')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rentcar.touristplace', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Фото места',
                'verbose_name_plural': 'Фото мест',
            },
        ),
    ]
